const removeSelectors = [
    'Price to Earning',
    'Dividend yield',
    'Net Profit latest quarter',
    'YOY Quarterly sales growth',
    'YOY Quarterly profit growth',
    'Sales latest quarter',
    'Return on capital employed'
];

const cols = [
    'Market Capitalization 3years back',
    'Market Capitalization 5years back',
    'mc50', 'mc200', 'mc200Diff', 'mc1',
    'Price to Earning',
    'PER',
    'GN',
    'Earnings yield',
    'Price to Sales',
    'Price to Free Cash Flow',
    'Price to Cash Flow',
    'EVEBITDA',
    'Interest Coverage Ratio',
    'Debt to equity',
    'Current ratio',
    'Free cash flow last year',
    'Free cash flow preceding year',
    'Free cash flow 3years',
    'QoQ Profits',
    'QoQ Sales',
    'YOY Quarterly profit growth',
    'Free cash flow 5years',
    'Return on equity',
    'Return on equity preceding year',
    'Average return on equity 3Years',
    'Average return on equity 5Years',
    'Return on capital employed',
    'Return on capital employed preceding year',
    'Average return on capital employed 3Years',
    'Average return on capital employed 5Years',
    'Sales growth',
    'YOY Quarterly sales growth',
    'Sales growth 3Years',
    'Sales growth 5Years',
    'EPS',
    'EPS last year',
    'EPS preceding year',
    'EPS latest quarter',
    'EPS preceding quarter',
    'EPS preceding year quarter',
    'Dividend yield',
    'Dividend Payout Ratio',
    'Return on assets',
    'Return on assets preceding year',
    'Return on assets 3years',
    'Return on assets 5years',
    'OPM',
    'OPM last year',
    'OPM preceding year',
    'OPM latest quarter',
    'OPM preceding quarter',
    'OPM preceding year quarter',
    'Inventory turnover ratio',
    'NPM last year',
    'NPM preceding year',
    'NPM latest quarter',
    'NPM preceding quarter',
    'NPM preceding year quarter',
    'Return over 3months',
    'Return over 1year'
];

module.exports = {
    removeSelectors,
    cols
}