module.exports = {
    //cols: ['openClosePer', 'prevClosePer', 'prevOpenPer', 'trdQtyPer', 'turnoverPer', 'noOfTradePer'],
    //cols: ['openClosePer', 'prevClosePer', 'prevOpenPer', 'noOfTradePer'],
	
	cols: ['openClosePer', 'prevClosePer', 'prevOpenPer'],
	//cols: ['openClosePer', 'prevCloseOpenPer'],
	
	
	
    colSymbol: 'Symbol',
	colPrice:'Prev Close',
    colDate: 'Date',
    n50q: ["DALBHARAT"],
    n50: [
        'ONGC',
        'NTPC',
        'TATASTEEL',
        'UPL',
        'POWERGRID',
        'ICICIBANK',
        'SBILIFE',
        'BPCL',
        'EICHERMOT',
        'RELIANCE',
        'GRASIM',
        'COALINDIA',
        'SBIN',
        'HINDALCO',
        'JSWSTEEL',
        'ASIANPAINT',
        'BRITANNIA',
        'ITC',
        'HDFCLIFE',
        'BAJAJFINSV',
        'AXISBANK',
        'BAJAJ-AUTO',
        'BHARTIARTL',
        'HDFC',
        'TATAMOTORS',
        'TITAN',
        'DRREDDY',
        'HDFCBANK',
        'INDUSINDBK',
        'M&M',
        'SHREECEM',
        'BAJFINANCE',
        'ULTRACEMCO',
        'ADANIPORTS',
        'WIPRO',
        'TCS',
        'KOTAKBANK',
        'HCLTECH',
        'NESTLEIND',
        'SUNPHARMA',
        'HINDUNILVR',
        'LT',
        'TECHM',
        'HEROMOTOCO',
        'CIPLA',
        'TATACONSUM',
        'MARUTI',
        'INFY',
        'APOLLOHOSP',
        'DIVISLAB'
    ],
	next50:["PIIND",
"BANKBARODA",
"BOSCHLTD",
"MOTHERSON",
"ADANIGREEN",
"BAJAJHLDNG",
"BANDHANBNK",
"TATAPOWER",
"PIDILITIND",
"SBICARD",
"INDUSTOWER",
"HDFCAMC",
"DABUR",
"VEDL",
"ZOMATO",
"MUTHOOTFIN",
"BIOCON",
"COLPAL",
"DMART",
"DLF",
"LICI",
"IRCTC",
"ATGL",
"MARICO",
"CHOLAFIN",
"IOC",
"SIEMENS",
"LTI",
"AMBUJACEM",
"ICICIGI",
"PGHH",
"PAYTM",
"TORNTPHARM",
"BEL",
"SRF",
"NAUKRI",
"MPHASIS",
"SHREECEM",
"GLAND",
"ADANITRANS",
"GODREJCP",
"ACC",
"GAIL",
"MCDOWELL-N",
"HAVELLS",
"ICICIPRULI",
"INDIGO",
"HAL",
"BERGEPAINT",
"NYKAA"]
}