module.exports = {
    //cols: ['openClosePer', 'prevClosePer', 'prevOpenPer', 'trdQtyPer', 'turnoverPer', 'noOfTradePer'],
    //cols: ['openClosePer', 'prevClosePer', 'prevOpenPer', 'trdQtyPer'],
	cols: ['openClosePer', 'prevClosePer', 'prevOpenPer'],
    colSymbol: 'Symbol',
	colPrice:'Prev Close',
    colDate: 'Date',
    n50q: ["TATASTEEL", "WIPRO"],
    n50: [
        'ONGC',
        'NTPC',
        'TATASTEEL',
        'UPL',
        'POWERGRID',
        'ICICIBANK',
        'SBILIFE',
        'BPCL',
        'EICHERMOT',
        'RELIANCE',
        'GRASIM',
        'COALINDIA',
        'SBIN',
        'HINDALCO',
        'JSWSTEEL',
        'ASIANPAINT',
        'BRITANNIA',
        'ITC',
        'HDFCLIFE',
        'BAJAJFINSV',
        'AXISBANK',
        'BAJAJ-AUTO',
        'BHARTIARTL',
        'HDFC',
        'TATAMOTORS',
        'TITAN',
        'DRREDDY',
        'HDFCBANK',
        'INDUSINDBK',
        'M&M',
        'SHREECEM',
        'BAJFINANCE',
        'ULTRACEMCO',
        'ADANIPORTS',
        'WIPRO',
        'TCS',
        'KOTAKBANK',
        'HCLTECH',
        'NESTLEIND',
        'SUNPHARMA',
        'HINDUNILVR',
        'LT',
        'TECHM',
        'HEROMOTOCO',
        'CIPLA',
        'TATACONSUM',
        'MARUTI',
        'INFY',
        'APOLLOHOSP',
        'DIVISLAB'
    ]
}